################################################################################
#                                                                              #
#                               leaps_share.yaml                               #
#                               ================                               #
#                                                                              #
# This is a configuration for sharing the files in a directory simply by       #
# navigating to that directory and running leaps.                              #
#                                                                              #
# You can then edit any of the files using the web interface at                #
# http://localhost:8001                                                        #
#                                                                              #
# To invite other engineers to edit with you simply link them to your LAN IP   #
# (e.g. http://192.168.0.134:8001)                                             #
#                                                                              #
# There are three important set up steps:                                      #
# - Install leaps using the ./install.sh script                                #
# - Copy this configuration into /etc/leaps/config.yaml                        #
#                                                                              #
# Then use it like this:                                                       #
#  ( cd /dir/that/i/want/to/share && leaps )                                   #
#                                                                              #
################################################################################

logger:
  prefix: '[leaps]'
stats:
  prefix: leaps
  retain_internal: true
storage:
  type: file
  store_directory: .
authenticator:
  type: file
  file_config:
    share_path: .
    path: /files
http_server:
  static_path: /
  socket_path: /socket
  address: :8001
  www_dir: /etc/leaps/www/share_dir
