logger:
  prefix: 'leaps'
stats:
  prefix: leaps
storage:
  type: file
  store_directory: ./
authenticator:
  type: none
  allow_creation: true
curator:
  binder:
    flush_period_ms: 10000
    retention_period_s: 60
    kick_period_ms: 200
    close_inactivity_period_s: 300
    transform_model:
      max_document_size: 50000000
      max_transform_length: 50000
http_server:
  static_path: /
  socket_path: /socket
  address: :8001
  www_dir: ../static/example_file
  binder:
    bind_send_timeout_ms: 10
admin_server:
  static_path: /
  path: /
  address: localhost:4040
  www_dir: ../static/stats
