logger:
  prefix: 'leaps'
  log_level: INFO
  add_timestamp: true
stats:
  prefix: leaps
  retain_internal: true
storage:
  type: azureblobstorage
  azure:
    account: ACCOUNT_NAME
    secret:  ACCOUNT_KEY
    container: leaps
authenticator:
  type: none
  allow_creation: true
curator:
  binder:
    flush_period_ms:    60000
http_server:
  static_path: /
  socket_path: /socket
  address: :8001
  www_dir: ../static/example
stats_server:
  static_path: /
  stats_path: /stats
  address: :4040
  www_dir: ../static/stats
