#!/bin/sh
### BEGIN INIT INFO
# Provides: Leaps
# Required-Start: $local_fs $network $named $time $syslog
# Required-Stop: $local_fs $network $named $time $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Leaps is a service that hosts collaborative and shared documents for important people.
### END INIT INFO

DAEMON=/usr/sbin/leaps
NAME=leaps

RUNAS=leaps
CONFIG=/etc/leaps.yaml

PID=/var/run/leaps.pid
LOG=/var/log/leaps.log

test -x $DAEMON || exit 0

# Start the service
start() {
		if [ -f "$PID" ] && kill -0 $(cat "$PID"); then
			echo 'Service already running' >&2
			return 1
		fi
		echo 'Starting service...' >&2
		touch $LOG
		chown $RUNAS $LOG
		local CMD="$DAEMON -c $CONFIG &>> \"$LOG\" & echo \$!"
		su -c "$CMD" $RUNAS > "$PID"
        echo 'Service started' >&2
}
# Stop the service
stop() {
		if [ ! -f "$PID" ]; then
			echo 'Service not running' >&2
			return 1
		fi
		if [ true ] && ! kill -0 $(cat "$PID"); then
			rm -f "$PID"
			echo 'Service not running' >&2
			return 1
		fi
		echo 'Stopping service...' >&2
		kill -15 $(cat "$PID") && rm -f "$PID"
		echo 'Service stopped' >&2
}
# Check the status of the service
status() {
	echo "Checking $NAME..." >&2
	if [ -f $PID ]; then
		PID_VAL=`cat $PID`
		if [ -z "`ps axf | grep ${PID_VAL} | grep -v grep`" ]; then
			echo "Process dead but pidfile exists" >&2
		else
			echo "Running" >&2
		fi
	else
		echo "Service not running" >&2
	fi
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac
exit 0
